# ---------------------------------------------------------
# vChat - Configuraci√≥n Principal
# ---------------------------------------------------------

# Logging (Registro de Violaciones)
logging:
  enabled: true
  file: "violations.log"
  # Variables: %date%, %player%, %reason%, %message%
  format: "[%date%] Player: %player% | Reason: %reason% | Original: %message%"

# Sonidos Generales
sounds:
  reload: "ENTITY_PLAYER_LEVELUP"
  blocked: "BLOCK_NOTE_BLOCK_BASS"
  toggle-on: "BLOCK_NOTE_BLOCK_PLING"
  toggle-off: "BLOCK_NOTE_BLOCK_BASS"
